INSERT INTO galaxy (
    name,
    apparent_magnitude,
    type,
    age_in_billions_of_years,
    description
) VALUES
    ('Milky Way', null, 'spiral', 13.61, 'Milky Way Galaxy, large spiral system consisting of several hundred billion stars, one of which is the Sun. It takes its name from the Milky Way, the irregular luminous band of stars and gas clouds that stretches across the sky as seen from Earth. Although Earth lies well within the Milky Way Galaxy (sometimes simply called the Galaxy), astronomers do not have as complete an understanding of its nature as they do of some external star systems.'),
    ('Andromeda Galaxy', 3.44, 'spiral', 10.01, 'Andromeda Galaxy, also called Andromeda Nebula, (catalog numbers NGC 224 and M31), great spiral galaxy in the constellation Andromeda, the nearest large galaxy. The Andromeda Galaxy is one of the few visible to the unaided eye, appearing as a milky blur. It is located about 2,480,000 light-years from Earth; its diameter is approximately 200,000 light-years; and it shares various characteristics with the Milky Way system.'),
    ('Black Eye Galaxy', 8.52, 'spiral', 13.28, 'Easily identified by the spectacular band of absorbing dust partially obscuring its bright nucleus, M64, or the Black Eye galaxy, is characterized by its bizarre internal motion. The gas in the outer regions of this remarkable galaxy is rotating in the opposite direction from the gas and stars in its inner regions.'),
    ('Comet Galaxy', 18.7, 'spiral', null, 'The Comet Galaxy, a spiral galaxy located 3.2 billion light-years from Earth, in the galaxy cluster Abell 2667, was found with the Hubble Space Telescope. This galaxy has slightly more mass than our Milky Way. It was detected on 2 March 2007. Comet Galaxy. The Comet Galaxy, as taken by the Hubble Space Telescope.'),
    ('Centaurus A', 6.84, 'elliptical', 13.27, 'Centaurus A, also known as NGC 5128, is a peculiar massive elliptical galaxy with a supermassive black hole at its heart. It lies about 12 million light-years away in the southern constellation of Centaurus (The Centaur) and has the distinction of being the most prominent radio galaxy in the sky. Astronomers think that the bright nucleus, strong radio emission and jet features of Centaurus A are produced by a central black hole with a mass of about 100 million times that of the Sun. Matter from the dense central parts of the galaxy releases vast amounts of energy as it falls towards the black hole.'),
    ('Whirlpool Galaxy', 8.4, 'spiral', 0.4003, 'The graceful, winding arms of the majestic spiral galaxy M51 appear like a grand spiral staircase sweeping through space. They are actually long lanes of stars and gas laced with dust. Such striking arms are a hallmark of so-called grand-design spiral galaxies. In M51, also known as the Whirlpool galaxy, these arms serve an important purpose: they are star-formation factories, compressing hydrogen gas and creating clusters of new stars.');
